// Global scope

const func = ((num) => {
  return num * 2;
}) satisfies (num: number) => number;

const f1 = (() => 3) satisfies () => number,
  f2 = (() => "a") satisfies () => string;

// In a function
function func2() {
  // a

  const foo = (() => {
    // long function...
    // long function...
    // long function...
    // long function...
    // long function...
    // long function...
    // long function...
    // long function...
    return 3;
  }) satisfies () => number;
}

// Class field
class A {
  // a

  func = ((num) => {
    // long function...
    // long function...
    // long function...
    // long function...
    // long function...
    // long function...
    // long function...
    // long function...
    return "foo" as const;
  }) satisfies (num: number) => string;
}

// In a object literal
const obj = {
  // a

  field: (() => {
    return 3;
  }) satisfies () => number,
};
